// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "FindTheApple",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "FindTheApple",
            targets: ["AppModule"],
            bundleIdentifier: "AndrewBaki.FindTheApple",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/danielgindi/Charts.git", "5.1.0"..<"6.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "DGCharts", package: "charts"),
                .product(name: "DGChartsDynamic", package: "charts")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)